export type Lang = 'th' | 'en';
export type Localized = Record<Lang, string>;
export const text = (th: string, en: string): Localized => ({ th, en });
export const sources = {
  tat: 'https://www.tourismthailand.org/Articles/1-day-in-talat-noi',
  church: 'https://www.thailandtravel.or.jp/holy-rosary-church/',
  museum: 'https://emuseum-taladnoi.treasury.go.th/about-us/',
};
export const mapUrl = (name = 'Talat Noi Bangkok') => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;
export const places = [
  { id: 'so-heng-tai', name: text('บ้านโซวเฮงไถ่', 'So Heng Tai'), category: text('สถาปัตยกรรม · ครอบครัว', 'Architecture · Family'), color: '#44523C', map: 'So Heng Tai Mansion Bangkok', source: sources.tat, sourceName: text('การท่องเที่ยวแห่งประเทศไทย — ข้อมูลสถานที่', 'Tourism Authority of Thailand — Place information'), facts: text('บ้านจีนเก่าในตลาดน้อยที่มีผังรูปตัวยู ข้อมูล ททท. กล่าวถึงการปรับใช้พื้นที่เป็นคาเฟ่และกิจกรรมดำน้ำในลานกลางบ้าน', 'An old Chinese house in Talat Noi with a U-shaped layout. TAT describes its adaptation as a café and a venue for diving activities in the courtyard.'), story: text('บ้านที่มีชีวิต', 'A house with a living story'), storyIntro: text('พื้นที่เก่าและการใช้งานปัจจุบัน ช่วยให้เราอ่านชุมชนได้มากขึ้น', 'Old spaces and present-day uses help us read the community in a new way.') },
  { id: 'chow-sue-kong', name: text('ศาลเจ้าโจวซือกง', 'Chow Sue Kong Shrine'), category: text('ความเชื่อ · ชุมชน', 'Belief · Community'), color: '#A52219', map: 'Chow Sue Kong Shrine Bangkok', source: sources.tat, sourceName: text('การท่องเที่ยวแห่งประเทศไทย — ข้อมูลสถานที่', 'Tourism Authority of Thailand — Place information'), facts: text('ศาลเจ้าที่สัมพันธ์กับชุมชนชาวจีนฮกเกี้ยน ตั้งอยู่ริมแม่น้ำเจ้าพระยาในย่านตลาดน้อย อ่านเรื่องความเชื่อควบคู่กับบริบทของชุมชน', 'A shrine connected to the Hokkien Chinese community, beside the Chao Phraya River in Talat Noi. Read its religious significance alongside the context of the community.'), story: text('ความเชื่อที่เชื่อมชุมชน', 'Belief that connects a community'), storyIntro: text('อ่านความสัมพันธ์ของศาสนสถานกับผู้คนในย่าน', 'Explore the relationship between a sacred place and its community.') },
  { id: 'holy-rosary', name: text('โบสถ์กาลหว่าร์', 'Holy Rosary Church'), category: text('วัฒนธรรม · ประวัติศาสตร์', 'Culture · History'), color: '#8F8061', map: 'Holy Rosary Church Bangkok', source: sources.church, sourceName: text('การท่องเที่ยวแห่งประเทศไทย — Holy Rosary Church', 'Tourism Authority of Thailand — Holy Rosary Church'), facts: text('โบสถ์ริมเจ้าพระยาที่มีสถาปัตยกรรมกอทิกรีไววัล อาคารปัจจุบันเสร็จในปี 1897 ตามข้อมูล ททท. หน้าต่างกระจกสีเป็นหนึ่งในรายละเอียดที่โดดเด่น', 'A Gothic Revival church beside the Chao Phraya. According to TAT, the current building was completed in 1897. Its stained-glass windows are a distinctive detail.'), story: text('แสงสีในพื้นที่แห่งความเชื่อ', 'Light and colour in a sacred space'), storyIntro: text('มองสถาปัตยกรรมผ่านแสง รูปทรง และการใช้งาน', 'Read architecture through light, form and use.') },
  { id: 'industrial-heritage', name: text('ร่องรอยอุตสาหกรรมเก่า', 'Industrial heritage'), category: text('งาน · การค้า', 'Work · Trade'), color: '#47443E', map: 'Talat Noi Museum Bangkok', source: sources.museum, sourceName: text('กรมธนารักษ์ — พิพิธตลาดน้อย', 'Treasury Department — Talat Noi Museum'), facts: text('พิพิธตลาดน้อยเล่าเรื่องเศรษฐกิจและสังคมของย่าน พื้นที่มีบริบทของโรงกลึงและการค้าอะไหล่เก่า ข้อมูลมาจากกรมธนารักษ์ ผู้ดูแลพิพิธภัณฑ์', 'Talat Noi Museum tells the economic and social story of the neighbourhood, including the context of machine shops and the trade in used parts. Information is sourced from the Treasury Department, which manages the museum.'), story: text('จากโรงกลึงสู่เรื่องเล่าของย่าน', 'From machine shops to neighbourhood stories'), storyIntro: text('อ่านประวัติศาสตร์ผ่านพิพิธตลาดน้อย', 'Read local history through Talat Noi Museum.') },
];
export const objects = [
  { id: 'windows', name: text('หน้าต่าง', 'Windows'), intro: text('รูปทรงที่เปิดรับแสงและอากาศ', 'Forms that welcome light and air'), color: '#44523C', questions: [text('ช่องเปิดถูกแบ่งเป็นกี่ส่วน?', 'How is the opening divided?'), text('วัสดุและร่องรอยบอกอะไรเกี่ยวกับการใช้งาน?', 'What do materials and marks tell you about its use?'), text('แสงและอากาศสัมพันธ์กับพื้นที่ภายในอย่างไร?', 'How do light and air connect to the interior?')] },
  { id: 'doors', name: text('ประตู', 'Doors'), intro: text('ขอบเขตระหว่างภายในกับภายนอก', 'The boundary between inside and outside'), color: '#8D684B', questions: [text('ประตูแบ่งพื้นที่อย่างไร?', 'How does the door divide space?'), text('มีร่องรอยการเปิดปิดหรือการซ่อมแซมแบบใด?', 'What marks of use or repair can you see?'), text('ทางเข้าสัมพันธ์กับพื้นที่โดยรอบอย่างไร?', 'How does the entrance relate to its surroundings?')] },
  { id: 'shop-signs', name: text('ป้ายร้าน', 'Shop signs'), intro: text('ตัวอักษรที่เล่าเรื่องการค้า', 'Lettering that tells stories of trade'), color: '#A52219', questions: [text('ป้ายเลือกใช้ตัวอักษรแบบใด?', 'What kind of lettering does the sign use?'), text('สีและวัสดุช่วยสื่อสารอะไร?', 'What do its colours and materials communicate?'), text('ป้ายเชื่อมกับกิจการและชุมชนอย่างไร?', 'How does the sign connect to the business and community?')] },
];
export const copy = {
  explore: text('สำรวจ', 'Explore'), stories: text('เรื่องราว', 'Stories'), map: text('แผนที่', 'Map'), about: text('เกี่ยวกับ', 'About'), objects: text('สิ่งของ', 'Objects'), places: text('สถานที่', 'Places'), all: text('ทั้งหมด', 'All'), list: text('รายการ', 'List'),
  search: text('ค้นหาสถานที่หรือเรื่องราว', 'Search places, objects or stories'), read: text('อ่านเรื่องราว →', 'Read the story →'), look: text('มองให้ใกล้ →', 'Look closer →'), symbolic: text('ภาพประกอบเชิงสัญลักษณ์', 'Symbolic illustration'),
  visit: text('ก่อนออกเดินทาง', 'Before you visit'), visitText: text('ตรวจเวลาเข้าชมและเงื่อนไขจากช่องทางของสถานที่ เคารพกิจกรรมของชุมชน และขออนุญาตก่อนถ่ายภาพในพื้นที่ส่วนตัว', 'Check opening times and access conditions directly with the venue. Respect community activities and ask permission before taking photographs in private spaces.'),
  directions: text('เปิดเส้นทางใน Google Maps', 'Open directions in Google Maps'), checked: text('ตรวจแหล่งข้อมูลออนไลน์: 7 ตุลาคม 2026', 'Sources reviewed online: 7 October 2026'),
};
