import { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { copy, mapUrl, objects, places, sources, type Lang } from './data';
import { ObjectArt, PlaceArt } from './Art';
import { External, PageHead, PlaceCard, Schematic, path } from './ui';

export function Home({ lang }: { lang: Lang }) {
  const th = lang === 'th';
  return <>
    <section className="container home-hero"><div><p className="kicker">{th ? 'ตลาดน้อย กรุงเทพฯ • สำรวจวัฒนธรรมผ่านเรื่องราว' : 'Talat Noi, Bangkok · Culture through stories'}</p><h1>{th ? 'มองให้ใกล้' : 'Look closer'}<br/>{th ? 'ค้นพบให้มากขึ้น' : 'Discover more'}</h1><p className="hero-description">{th ? 'อ่านสถานที่ สิ่งของ และเรื่องเล่า' : 'Read places, objects and stories'}<br/>{th ? 'เพื่อค้นพบรายละเอียดที่เคยมองผ่าน' : 'Discover the details you once walked past'}</p><Link className="button" to={path(lang, 'explore')}>{th ? 'เริ่มสำรวจ →' : 'Start exploring →'}</Link></div><PlaceArt lang={lang}/></section>
    <div className="culture-band"><div className="container"><strong>{th ? 'วัฒนธรรม × ชุมชน × ประสบการณ์ที่มีชีวิต' : 'Culture × Community × Living experiences'}</strong><span>{th ? 'ทุกเรื่องเชื่อมกับพื้นที่จริง' : 'Every story connects to a real place'}</span></div></div>
    <section className="container home-explore"><p className="kicker">01 / {copy.explore[lang]}</p><h2>{th ? 'อะไรคือสิ่งแรกที่คุณสังเกตเห็น?' : 'What is the first thing you notice?'}</h2><div className="tabs"><Link className="pill active" to={path(lang, 'explore')}>{copy.places[lang]}</Link><Link className="pill" to={path(lang, 'objects')}>{copy.objects[lang]}</Link><Link className="pill" to={path(lang, 'stories')}>{copy.stories[lang]}</Link></div><div className="home-place-grid">{places.map((p, i) => <Link key={p.id} className={`home-place home-place-${i}`} to={path(lang, `places/${p.id}`)}><span className="kicker">0{i + 1}</span><h3>{p.name[lang]}</h3><p>{p.category[lang]}</p><span className="text-link">{copy.read[lang]}</span></Link>)}</div></section>
    <section className="closer-band"><div className="container closer-inner"><div><p className="kicker light">02 / {th ? 'มองให้ใกล้' : 'Look closer'}</p><h2>{th ? 'รายละเอียดเล็ก ๆ' : 'Small details'}<br/>{th ? 'เรื่องราวที่ใหญ่กว่า' : 'Bigger stories'}</h2><p>{th ? 'ลองเริ่มจากหน้าต่าง ประตู และป้ายร้าน' : 'Start with windows, doors and shop signs'}</p></div><Link className="closer-card" to={path(lang, 'objects/windows')}><span className="kicker">{th ? 'มองให้ใกล้ / 01' : 'Look closer / 01'}</span><h3>{objects[0].name[lang]}</h3><p>{th ? 'อ่านแสง อากาศ และพื้นที่ภายใน' : 'Read light, air and interior space'}</p><span className="text-link">{th ? 'เปิดจุดสังเกต →' : 'Explore the detail →'}</span></Link></div></section>
    <section className="container past-section"><p className="kicker">03 / {th ? 'อดีต × ปัจจุบัน' : 'Past × Present'}</p><h2>{th ? 'เมื่ออดีตพบกับปัจจุบัน' : 'When the past meets the present'}</h2><div className="past-grid"><Link to={path(lang, 'places/industrial-heritage')}><h3>{th ? 'บริบทของย่าน' : 'The neighbourhood context'}</h3><p>{th ? 'จากโรงกลึงและการค้าอะไหล่' : 'From machine shops and the trade in parts'}</p><span className="text-link">{th ? 'อ่านประวัติศาสตร์ผ่านพิพิธตลาดน้อย →' : 'Read history through Talat Noi Museum →'}</span></Link><Link to={path(lang, 'places/so-heng-tai')}><h3>{th ? 'การใช้งานปัจจุบัน' : 'Present-day uses'}</h3><p>{th ? 'พื้นที่เก่ากับกิจกรรมร่วมสมัย' : 'Old spaces and contemporary activities'}</p><span>{th ? 'อ่านเรื่องบ้านโซวเฮงไถ่ →' : 'Read the story of So Heng Tai →'}</span></Link></div></section>
    <section className="trust-band"><div className="container"><div><h2>{th ? '04 / เรื่องราวที่เชื่อถือได้' : '04 / Stories with sources'}</h2><p>{th ? 'ระบุที่มาและวันที่ตรวจสอบ เพื่อให้คุณอ่านต่อได้' : 'Sources and review dates, so you can keep reading'}</p></div><Link className="button cream" to={path(lang, 'about')}>{th ? 'ที่มาและวิธีตรวจสอบ →' : 'Sources and our approach →'}</Link></div></section>
  </>;
}

type Result = { id: string; title: string; subtitle: string; to: string; kind: string; index: number; keywords: string };
export function searchItems(lang: Lang): Result[] {
  return [...places.map((p, i) => ({ id: p.id, title: p.name[lang], subtitle: p.category[lang], to: `places/${p.id}`, kind: 'places', index: i, keywords: `${p.name.th} ${p.name.en} ${p.category.th} ${p.category.en}` })), ...objects.map((p, i) => ({ id: p.id, title: p.name[lang], subtitle: p.intro[lang], to: `objects/${p.id}`, kind: 'objects', index: i, keywords: `${p.name.th} ${p.name.en} ${p.intro.th} ${p.intro.en}` })), ...places.map((p, i) => ({ id: 'story-' + p.id, title: p.story[lang], subtitle: p.name[lang], to: `stories/${p.id}`, kind: 'stories', index: i, keywords: `${p.story.th} ${p.story.en} ${p.name.th} ${p.name.en}` }))];
}
export function Explore({ lang }: { lang: Lang }) {
  const [params, setParams] = useSearchParams();
  const query = params.get('q') || '';
  const category = ['places', 'objects', 'stories'].includes(params.get('type') || '') ? params.get('type')! : 'all';
  const th = lang === 'th';
  const candidates = searchItems(lang).filter(p => category === 'all' || p.kind === category);
  const normalized = query.normalize('NFKC').trim().toLocaleLowerCase();
  const results = candidates.filter(p => !normalized || p.keywords.normalize('NFKC').toLocaleLowerCase().includes(normalized));
  function change(key: string, value: string) { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next, { replace: true }); }
  return <section className="container page-content"><PageHead kicker={th ? '01 / สำรวจตลาดน้อย' : '01 / Explore Talat Noi'} title={th ? 'เริ่มจากสิ่งที่คุณสนใจ' : 'Start with what interests you'} description={th ? 'สถานที่ สิ่งของ และเรื่องเล่า เชื่อมต่อกันในย่านเดียว' : 'Places, objects and stories, connected in one neighbourhood'}><label className="search-field"><span className="sr-only">{copy.search[lang]}</span><input type="search" placeholder={copy.search[lang]} value={query} onChange={e => change('q', e.target.value)}/><span aria-hidden="true">⌕</span></label></PageHead><div className="explore-controls"><div className="tabs" aria-label={th ? 'ประเภทเนื้อหา' : 'Content type'}>{(['all', 'places', 'objects', 'stories'] as const).map(c => <button key={c} className={`pill ${category === c ? 'active' : ''}`} onClick={() => change('type', c === 'all' ? '' : c)} aria-pressed={category === c}>{copy[c][lang]}</button>)}</div><div className="tabs view-switch"><span className="pill active">{copy.list[lang]}</span><Link className="pill" to={path(lang, 'map')}>{copy.map[lang]}</Link></div></div>
      <p className="result-count" aria-live="polite">{th ? `${results.length} ${query ? 'รายการที่ตรงกับคำค้น' : 'จุดเริ่มต้นสำหรับการสำรวจ'}` : `${results.length} ${query ? 'matching results' : 'starting points to explore'}`}</p>
      {results.length ? <div className="explore-grid"><div className="result-list">{results.map(r => r.kind === 'places' ? <PlaceCard key={r.id} index={r.index} lang={lang}/> : <Link key={r.id} className="place-card" to={path(lang, r.to)}><span className="number" style={{ background: r.kind === 'objects' ? '#A52219' : '#44523C' }}>{String(r.index + 1).padStart(2, '0')}</span><span className="place-card-text"><strong>{r.title}</strong><span>{r.subtitle}</span></span><span className="arrow">→</span></Link>)}</div><aside className="explore-map"><Schematic lang={lang}/><External href={mapUrl()} className="button green wide">{th ? 'เปิดแผนที่จริงและวางแผนเส้นทาง' : 'Open the real map and plan your route'}</External></aside></div> : <div className="empty-state"><h2>{th ? 'ไม่พบรายการที่ตรงกับคำค้น' : 'No matching results'}</h2><p>{th ? 'ลองคำอื่น หรือเริ่มสำรวจใหม่' : 'Try another word or start exploring again'}</p><button className="button" onClick={() => setParams({})}>{th ? 'กลับไปสำรวจทั้งหมด →' : 'Explore all places →'}</button></div>}
      <p className="fine-print">{th ? 'เลือกการ์ดหรือจุดบนแผนผังเพื่อดูเรื่องราว' : 'Choose a card or a point on the diagram to read its story'}</p>
    </section>;
}

export function MapPage({ lang }: { lang: Lang }) {
  const [selected, setSelected] = useState(0);
  const th = lang === 'th';
  return <section className="container page-content"><PageHead kicker={th ? '02 / แผนที่ตลาดน้อย' : '02 / Talat Noi map'} title={th ? 'เรื่องราวอยู่ใกล้กว่าที่คิด' : 'Stories are closer than you think'} description={th ? 'เลือกจุดบนแผนผัง แล้วเปิดเส้นทางจริงก่อนออกเดินทาง' : 'Choose a point on the diagram, then open real directions before you visit'}/><div className="map-page-grid"><div><Link className="pill" to={path(lang, 'explore')}>{th ? '← ดูแบบรายการ' : '← List view'}</Link><h2 className="small-heading">{th ? 'จุดเริ่มต้นของคุณ' : 'Your starting point'}</h2><div className="result-list">{places.map((p, i) => <button key={p.id} className={`place-card ${selected === i ? 'chosen' : ''}`} onClick={() => setSelected(i)} aria-pressed={selected === i}><span className="number" style={{ background: p.color }}>0{i + 1}</span><span className="place-card-text"><strong>{p.name[lang]}</strong><span>{p.category[lang]}</span></span><span className="arrow">→</span></button>)}</div></div><div><Schematic lang={lang} selected={selected} onSelect={setSelected}/><div className="selected-place" aria-live="polite"><strong>{places[selected].name[lang]}</strong><Link className="text-link" to={path(lang, `places/${places[selected].id}`)}>{copy.read[lang]}</Link></div><External className="button green wide" href={mapUrl(places[selected].map)}>{copy.directions[lang]}</External></div></div></section>;
}

export function Stories({ lang }: { lang: Lang }) {
  const th = lang === 'th';
  return <section className="container page-content"><PageHead kicker={th ? '03 / เรื่องราว' : '03 / Stories'} title={th ? 'มองผ่านรายละเอียด' : 'Look through the details'} description={th ? 'จากบ้านและศาสนสถาน สู่ความสัมพันธ์ของผู้คนกับพื้นที่' : 'From houses and sacred places to the relationship between people and space'}/><CategoryTabs lang={lang} active="stories"/><div className="story-feature"><PlaceArt lang={lang}/><Link to={path(lang, 'stories/so-heng-tai')} className="story-feature-copy"><span>{th ? 'เรื่องเด่น / สถาปัตยกรรม' : 'Featured / Architecture'}</span><h2>{places[0].story[lang]}</h2><h3>{places[0].name[lang]}</h3><p>{places[0].storyIntro[lang]}</p><strong>{copy.read[lang]}</strong></Link></div><div className="story-grid">{places.slice(1).map((p, i) => <Link key={p.id} to={path(lang, `stories/${p.id}`)} className="story-card"><div className="story-swatch" style={{ background: ['#A52219', '#988B71', '#44523C'][i] }}><span>0{i + 2}</span></div><h3>{p.name[lang]}</h3><p>{p.category[lang]}</p><span className="text-link">{th ? 'อ่านต่อ →' : 'Read more →'}</span></Link>)}</div><p className="fine-print">{th ? 'ทุกเรื่องเชื่อมกลับไปยังสถานที่และแหล่งข้อมูล' : 'Every story connects back to a place and its sources'}</p></section>;
}

function CategoryTabs({ lang, active }: { lang: Lang; active: string }) { return <div className="tabs category-tabs">{['stories', 'objects'].map(c => <Link className={`pill ${active === c ? 'active' : ''}`} to={path(lang, c)} key={c}>{copy[c as 'stories' | 'objects'][lang]}</Link>)}</div>; }

export function Objects({ lang }: { lang: Lang }) {
  const th = lang === 'th';
  return <section className="container page-content"><PageHead kicker={th ? '03 / สิ่งของและรายละเอียด' : '03 / Objects and details'} title={th ? 'รายละเอียดเล็ก ๆ ชวนให้มองใหม่' : 'Small details invite a new look'} description={th ? 'เริ่มสังเกตจากรูปทรง วัสดุ และร่องรอยการใช้งาน' : 'Start with form, materials and traces of use'}/><CategoryTabs lang={lang} active="objects"/><div className="object-grid">{objects.map((o, i) => <Link key={o.id} className="object-card" to={path(lang, `objects/${o.id}`)}><ObjectArt index={i} lang={lang}/><div><h2>{o.name[lang]}</h2><p>{o.intro[lang]}</p><span className="text-link">{copy.look[lang]}</span></div></Link>)}</div></section>;
}

export function PlaceDetail({ lang, story = false }: { lang: Lang; story?: boolean }) {
  const { id } = useParams();
  const index = places.findIndex(p => p.id === id);
  if (index < 0) return <NotFound lang={lang}/>;
  const p = places[index], th = lang === 'th';
  const factLines = th ? [
    ['บ้านจีนเก่าในตลาดน้อยที่มีผังรูปตัวยู', 'ข้อมูล ททท. กล่าวถึงการปรับใช้พื้นที่เป็นคาเฟ่', 'และกิจกรรมดำน้ำในลานกลางบ้าน'],
    ['ศาลเจ้าที่สัมพันธ์กับชุมชนชาวจีนฮกเกี้ยน', 'ตั้งอยู่ริมแม่น้ำเจ้าพระยาในย่านตลาดน้อย', 'อ่านเรื่องความเชื่อควบคู่กับบริบทของชุมชน'],
    ['โบสถ์ริมเจ้าพระยาที่มีสถาปัตยกรรมกอทิกรีไววัล', 'อาคารปัจจุบันเสร็จในปี 1897 ตามข้อมูล ททท.', 'หน้าต่างกระจกสีเป็นหนึ่งในรายละเอียดที่โดดเด่น'],
    ['พิพิธตลาดน้อยเล่าเรื่องเศรษฐกิจและสังคมของย่าน', 'พื้นที่มีบริบทของโรงกลึงและการค้าอะไหล่เก่า', 'ข้อมูลมาจากกรมธนารักษ์ ผู้ดูแลพิพิธภัณฑ์'],
  ][index] : [p.facts.en];
  return <article className="container place-detail"><Link className="back-link" to={path(lang, story ? 'stories' : 'explore')}>{th ? '← กลับไป' : '← Back to'} {story ? copy.stories[lang] : th ? 'สำรวจตลาดน้อย' : 'Explore Talat Noi'}</Link><div className="detail-hero"><div><p className="kicker">{story ? copy.stories[lang] : copy.places[lang]} / 0{index + 1}</p><h1>{story ? p.story[lang] : p.name[lang]}</h1><p className="lead">{p.category[lang]}</p><p className="location">{index === 3 ? th ? 'จุดแนะนำ: พิพิธตลาดน้อย' : 'Suggested stop: Talat Noi Museum' : th ? 'ตลาดน้อย • เขตสัมพันธวงศ์ • กรุงเทพฯ' : 'Talat Noi · Samphanthawong · Bangkok'}</p><External href={mapUrl(p.map)}>{copy.directions[lang]}</External></div><PlaceArt lang={lang} index={index} compact/></div><div className="detail-story"><div><p className="kicker">01 / {copy.stories[lang]}</p><h2>{th ? 'พื้นที่เก่า บริบทที่ยังมีชีวิต' : 'Old spaces, living context'}</h2><p className="body-copy">{factLines.map((line, i) => <span key={i}>{line}</span>)}</p>{story && <Link className="text-link" to={path(lang, `places/${p.id}`)}>{th ? 'ดูข้อมูลสถานที่ →' : 'View place information →'}</Link>}</div><Link className="detail-look" to={path(lang, index === 0 ? 'objects/windows' : 'objects')}><h2>{th ? 'มองให้ใกล้' : 'Look closer'}</h2><p>{th ? 'ลองอ่านรายละเอียดของรูปทรง' : 'Read the details of form'}</p><strong>{th ? 'เปิดจุดสังเกต →' : 'Explore the detail →'}</strong></Link></div><section className="visit-box"><div><h2>{copy.visit[lang]}</h2><p>{copy.visitText[lang]}</p></div><Link className="button green" to={path(lang, 'map')}>{th ? 'ดูจุดบนแผนผังย่าน →' : 'View the neighbourhood diagram →'}</Link></section><section className="source-section"><h2>{th ? 'แหล่งอ้างอิงและวันที่ตรวจสอบ' : 'Sources and review date'}</h2><External className="source-link" href={p.source}><strong>{p.sourceName[lang]}</strong><small>{copy.checked[lang]}</small></External></section></article>;
}

export function ObjectDetail({ lang }: { lang: Lang }) {
  const { id } = useParams(); const index = objects.findIndex(o => o.id === id);
  if (index < 0) return <NotFound lang={lang}/>;
  const o = objects[index], th = lang === 'th';
  return <article className="container page-content"><Link className="back-link" to={path(lang, 'objects')}>{th ? '← สิ่งของและรายละเอียด' : '← Objects and details'}</Link><PageHead kicker={th ? 'มองให้ใกล้' : 'Look closer'} title={o.name[lang]} description={o.intro[lang]}/><div className="object-detail-grid"><div className="object-illustration"><ObjectArt index={index} lang={lang}/><small>{copy.symbolic[lang]}</small></div><div><h2>{th ? 'อ่านรูปทรง ก่อนอ่านความหมาย' : 'Read the form before the meaning'}</h2><ol className="questions">{o.questions.map((q, i) => <li key={i}><span>0{i + 1}</span>{q[lang]}</li>)}</ol><Link className="button green" to={path(lang, 'places/so-heng-tai')}>{th ? 'อ่านเรื่องบ้านโซวเฮงไถ่ →' : 'Read about So Heng Tai →'}</Link></div></div><div className="illustration-note"><p>{th ? 'ภาพประกอบใช้เพื่อชวนสังเกต ไม่ใช่ภาพสำรวจอาคารจริง' : 'Illustrations invite observation; they are not survey photographs of real buildings.'}</p><Link className="text-link" to={path(lang, 'objects')}>{th ? 'ดูสิ่งของอื่น ๆ →' : 'Explore other objects →'}</Link></div></article>;
}

export function About({ lang }: { lang: Lang }) {
  const th = lang === 'th';
  return <section className="container page-content"><div className="about-hero"><div><p className="kicker">04 / {copy.about[lang]} NOI NOW</p><h1>{th ? 'มองให้ใกล้' : 'Look closer'}<br/>{th ? 'เพื่อเข้าใจให้มากขึ้น' : 'Understand more'}</h1></div><div><h2>{th ? 'พื้นที่อ่านและสำรวจวัฒนธรรมตลาดน้อย' : 'A space to read and explore Talat Noi culture'}</h2><p>{th ? 'เชื่อมสถานที่ สิ่งของ และเรื่องเล่าของผู้คน ให้รายละเอียดที่เคยมองผ่าน มีความหมายอีกครั้ง' : 'Connecting places, objects and people’s stories, so details once overlooked have meaning again.'}</p></div></div><div className="principles">{(th ? [['เริ่มจากพื้นที่จริง', 'เลือกสถานที่และรายละเอียดเป็นจุดเริ่มต้น แล้วเชื่อมโยงให้เห็นบริบทของย่าน'], ['อ่านอย่างมีที่มา', 'ระบุแหล่งข้อมูลที่ผู้อ่านตรวจสอบต่อได้ บอกวันที่ตรวจและแยกข้อเท็จจริงจากข้อสังเกต'], ['เคารพชุมชน', 'การไปเยือนควรเคารพเจ้าของพื้นที่ ขออนุญาตก่อนถ่ายภาพหรือเข้าพื้นที่ส่วนตัว']] : [['Start with real places', 'Begin with places and details, then connect them to the neighbourhood context.'], ['Read with sources', 'Identify sources readers can follow, state review dates and distinguish facts from observations.'], ['Respect the community', 'Respect the people who own and use these spaces. Ask permission before photographs or entry into private areas.']]).map(([h, p], i) => <div key={h}><span className="kicker">0{i + 1}</span><h2>{h}</h2><p>{p}</p></div>)}</div><section className="about-sources"><h2>{th ? 'แหล่งข้อมูลและการตรวจสอบ' : 'Sources and review'}</h2><p>{th ? 'เนื้อหาสถานที่อ้างอิงข้อมูลเผยแพร่ของหน่วยงานการท่องเที่ยวและกรมธนารักษ์' : 'Place information refers to published material from tourism authorities and the Treasury Department.'}</p><div><External href={sources.tat} className="source-tile">{th ? 'ททท. — 1 day in Talat Noi' : 'TAT — 1 day in Talat Noi'}</External><External href={sources.church} className="source-tile">{th ? 'ททท. — Holy Rosary Church' : 'TAT — Holy Rosary Church'}</External><External href={sources.museum} className="source-tile">{th ? 'กรมธนารักษ์ — พิพิธตลาดน้อย' : 'Treasury Department — Talat Noi Museum'}</External></div><p className="fine-print">{copy.checked[lang]} · {th ? 'ข้อมูลเข้าชมควรตรวจจากสถานที่ก่อนเดินทาง' : 'Confirm access information directly with venues before visiting'}</p></section></section>;
}
export function NotFound({ lang }: { lang: Lang }) { return <section className="container not-found"><p className="kicker">404</p><h1>{lang === 'th' ? 'ไม่พบหน้าที่คุณกำลังมองหา' : 'This page could not be found'}</h1><p>{lang === 'th' ? 'กลับไปเลือกสถานที่ สิ่งของ หรือเรื่องราวในตลาดน้อย' : 'Find a place, an object or a story in Talat Noi.'}</p><Link className="button" to={path(lang, 'explore')}>{lang === 'th' ? 'กลับไปสำรวจ →' : 'Back to explore →'}</Link></section>; }
